"use client";

import { Badge, BadgeText } from "./components/ui/badge";
import { Box } from "./components/ui/box";
import { HStack } from "./components/ui/hstack";
import { VStack } from "./components/ui/vstack";
import {
  Body,
  Button,
  Card,
  Eyebrow,
  Heading,
  Input,
  Section,
  StatusPill
} from "./primitives";

export function StarterModule() {
  return (
    <Box className="min-h-screen bg-background-0 px-6 py-12">
      <VStack className="mx-auto w-full max-w-[1080px]" space="xl">
        <Section>
          <StatusPill label="gluestack-ui v3" />
          <Heading>Basic shared components.</Heading>
          <Body>
            The shared package now renders official gluestack components in
            both Next.js and Expo. The component styling comes from the
            generated defaults, with only layout classes around the demo.
          </Body>
          <HStack className="flex-wrap" space="sm">
            <Button>Primary action</Button>
            <Button variant="secondary">Secondary action</Button>
            <Button variant="ghost">Ghost action</Button>
          </HStack>
        </Section>

        <HStack className="flex-wrap" space="md">
          <Card className="min-w-[280px] flex-1">
            <Eyebrow>Card</Eyebrow>
            <Heading size="xl">Default surface</Heading>
            <Body>
              Cards, headings, text, buttons, badges, stacks, and inputs are
              generated by the gluestack CLI.
            </Body>
          </Card>

          <Card className="min-w-[280px] flex-1" tone="accent">
            <Eyebrow>Form</Eyebrow>
            <Heading size="xl">Input primitive</Heading>
            <Input placeholder="Search components" />
            <HStack className="flex-wrap" space="sm">
              <Badge action="success">
                <BadgeText>Shared</BadgeText>
              </Badge>
              <Badge action="muted" variant="outline">
                <BadgeText>Default</BadgeText>
              </Badge>
            </HStack>
          </Card>
        </HStack>
      </VStack>
    </Box>
  );
}
